version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2021-06-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_*.feather
        
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.feather
        
  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py --output-format=feather
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input*.feather

  generate_data_description:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/data_description.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [join_ethnicity]
    outputs:
      moderately_sensitive:
        notebook: output/data_description.html

  # cohort_report:
  #   run: cohort-report:v2.0.1 output/data/input_joined.feather
  #   needs: [join_ethnicity]
  #   config:
  #     output_path: output/data
  #   outputs:
  #     moderately_sensitive:
  #       cohort_report: output/data/descriptives_input_joined.html
        
  # calculate_measures:
  #   run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/data
  #   needs: [join_ethnicity]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/data/measure_*.csv
        
  # generate_abnormal_nb:
  #   run: jupyter:latest jupyter nbconvert /workspace/notebooks/abnormal_results.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [calculate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/abnormal_results.html
        
  # generate_levels_nb:
  #   run: jupyter:latest jupyter nbconvert /workspace/notebooks/hba1c_levels.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [join_ethnicity]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/hba1c_levels.html