version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all_patients --index-date-range "2019-01-01 to 2021-06-01 by month" --output-dir=output/data 
    outputs:
      highly_sensitive:
        cohort: output/data/input_all_patients_*.csv

  generate_study_population_elev_predm:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_elev_predm --index-date-range "2019-01-01 to 2021-06-01 by month" --output-dir=output/data 
    outputs:
      highly_sensitive:
        cohort: output/data/input_elev_predm_*.csv

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data 
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.csv
        
  join_ethnicity_all_patients:
    run: python:latest python analysis/join_ethnicity.py "input_all_patients"
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input_all_patients*.csv

  join_ethnicity_elev_predm:
    run: python:latest python analysis/join_ethnicity.py "input_elev_predm"
    needs: [generate_study_population_elev_predm, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input_elev_predm*.csv

  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_all_patients --output-dir=output/data
    needs: [join_ethnicity_all_patients]
    outputs:
      moderately_sensitive:
        measure_csv: output/data/measure_*.csv

  redact_measures:
    run: python:latest python analysis/redact_measures.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        measure_csv: output/data/measure*.csv

  generate_data_description:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/data_description.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [join_ethnicity_all_patients]
    outputs:
      moderately_sensitive:
        notebook: output/data_description.html

  generate_elev_predm_inputs: 
    run: python:latest python analysis/elev_predm_input.py
    needs: [join_ethnicity_elev_predm]
    outputs:
      moderately_sensitive:
        cohorts1: output/data/calc_t2dm_elev*.csv
        cohorts2: output/data/calc_predm*.csv

  generate_charts:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/charts.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [redact_measures, generate_elev_predm_inputs]
    outputs:
      moderately_sensitive:
        notebook: output/charts.html

  generate_tables:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/tables.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [join_ethnicity_all_patients]
    outputs:
      moderately_sensitive:
        notebook: output/tables.html
